/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectone.ui;

import com.mycompany.projectone.ui.manager.BookManagerJDialog;
import com.mycompany.projectone.ui.manager.CategoryManagerJDialog;
import com.mycompany.projectone.ui.manager.CustomerManagerJDialog;
import com.mycompany.projectone.ui.manager.EmployeeManagerJDialog;
import com.mycompany.projectone.ui.manager.OrderManagerJDialog;
import com.mycompany.projectone.ui.manager.PaymentManagerJDialog;
import com.mycompany.projectone.ui.manager.PromotionManagerJDialog;
import com.mycompany.projectone.ui.manager.RevenueManagerJDialog;
import com.mycompany.projectone.util.XIcon;
/**
 *
 * @author WellyOwO
 */
public class MainUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfile = new javax.swing.JLabel();
        btnBookInfo = new javax.swing.JButton();
        btnCategories = new javax.swing.JButton();
        btnEmployees = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnRevenue = new javax.swing.JButton();
        btnPromotion = new javax.swing.JButton();
        btnExportInvoice = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnPayment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BOOKSTORE");
        setBackground(new java.awt.Color(174, 217, 224));
        setMaximumSize(new java.awt.Dimension(1200, 1400));
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblProfile.setBackground(new java.awt.Color(204, 204, 0));
        lblProfile.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblProfile.setForeground(new java.awt.Color(153, 153, 0));
        lblProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblProfile.setPreferredSize(new java.awt.Dimension(500, 500));
        lblProfile.setVerifyInputWhenFocusTarget(false);

        btnBookInfo.setBackground(new java.awt.Color(178, 176, 232));
        btnBookInfo.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnBookInfo.setForeground(new java.awt.Color(26, 42, 128));
        btnBookInfo.setText("THÔNG TIN SÁCH");
        btnBookInfo.setToolTipText("Nhấn để thao tác chức năng");
        btnBookInfo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnBookInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBookInfo.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnBookInfo.setFocusPainted(false);
        btnBookInfo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnBookInfo.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnBookInfo.setPreferredSize(null);
        btnBookInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookInfoActionPerformed(evt);
            }
        });

        btnCategories.setBackground(new java.awt.Color(178, 176, 232));
        btnCategories.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnCategories.setForeground(new java.awt.Color(26, 42, 128));
        btnCategories.setText("THỂ LOẠI SÁCH");
        btnCategories.setToolTipText("Nhấn để thao tác chức năng");
        btnCategories.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnCategories.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategories.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCategories.setFocusPainted(false);
        btnCategories.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnCategories.setPreferredSize(null);
        btnCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriesActionPerformed(evt);
            }
        });

        btnEmployees.setBackground(new java.awt.Color(178, 176, 232));
        btnEmployees.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnEmployees.setForeground(new java.awt.Color(26, 42, 128));
        btnEmployees.setText("THÔNG TIN NHÂN VIÊN");
        btnEmployees.setToolTipText("Nhấn để thao tác chức năng");
        btnEmployees.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmployees.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnEmployees.setFocusPainted(false);
        btnEmployees.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });

        btnCustomers.setBackground(new java.awt.Color(178, 176, 232));
        btnCustomers.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(26, 42, 128));
        btnCustomers.setText("THÔNG TIN KHÁCH HÀNG");
        btnCustomers.setToolTipText("Nhấn để thao tác chức năng");
        btnCustomers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomers.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnCustomers.setFocusPainted(false);
        btnCustomers.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        btnRevenue.setBackground(new java.awt.Color(178, 176, 232));
        btnRevenue.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnRevenue.setForeground(new java.awt.Color(26, 42, 128));
        btnRevenue.setText("BÁO CÁO DOANH THU");
        btnRevenue.setToolTipText("Nhấn để thao tác chức năng");
        btnRevenue.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnRevenue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRevenue.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnRevenue.setFocusPainted(false);
        btnRevenue.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueActionPerformed(evt);
            }
        });

        btnPromotion.setBackground(new java.awt.Color(178, 176, 232));
        btnPromotion.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnPromotion.setForeground(new java.awt.Color(26, 42, 128));
        btnPromotion.setText("CHƯƠNG TRÌNH KHUYẾN MÃI");
        btnPromotion.setToolTipText("Nhấn để thao tác chức năng");
        btnPromotion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnPromotion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPromotion.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnPromotion.setFocusPainted(false);
        btnPromotion.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnPromotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromotionActionPerformed(evt);
            }
        });

        btnExportInvoice.setBackground(new java.awt.Color(178, 176, 232));
        btnExportInvoice.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnExportInvoice.setForeground(new java.awt.Color(26, 42, 128));
        btnExportInvoice.setText("XUẤT HOÁ ĐƠN ");
        btnExportInvoice.setToolTipText("Nhấn để thao tác chức năng");
        btnExportInvoice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnExportInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportInvoice.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnExportInvoice.setFocusPainted(false);
        btnExportInvoice.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnExportInvoice.setPreferredSize(null);
        btnExportInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportInvoiceActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(178, 176, 232));
        btnExit.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnExit.setForeground(new java.awt.Color(26, 42, 128));
        btnExit.setText("THOÁT ỨNG DỤNG");
        btnExit.setToolTipText("Nhấn để thao tác chức năng");
        btnExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnExit.setFocusPainted(false);
        btnExit.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnChangePass.setBackground(new java.awt.Color(178, 176, 232));
        btnChangePass.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(26, 42, 128));
        btnChangePass.setText("ĐỔI MẬT KHẨU");
        btnChangePass.setToolTipText("Nhấn để thao tác chức năng");
        btnChangePass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnChangePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePass.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnChangePass.setFocusPainted(false);
        btnChangePass.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        btnPayment.setBackground(new java.awt.Color(178, 176, 232));
        btnPayment.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        btnPayment.setForeground(new java.awt.Color(26, 42, 128));
        btnPayment.setText("QUẢN LÝ THANH TOÁN");
        btnPayment.setToolTipText("Nhấn để thao tác chức năng");
        btnPayment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.LIGHT_GRAY, java.awt.Color.WHITE, java.awt.Color.YELLOW, java.awt.Color.ORANGE));
        btnPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayment.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnPayment.setFocusPainted(false);
        btnPayment.setMargin(new java.awt.Insets(10, 20, 10, 20));
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCategories, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPromotion, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExportInvoice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRevenue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBookInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnChangePass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)))
                .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnBookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExportInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnChangePass, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.ImageIcon icon = XIcon.getIcon("/Logo.png", 500, 550);
        lblProfile.setIcon(icon);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueActionPerformed
        RevenueManagerJDialog revenue = new RevenueManagerJDialog(new MainUI(), true);
        revenue.setVisible(true);
    }//GEN-LAST:event_btnRevenueActionPerformed

    private void btnBookInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookInfoActionPerformed
        BookManagerJDialog book = new BookManagerJDialog();
        book.setVisible(true);
    }//GEN-LAST:event_btnBookInfoActionPerformed

    private void btnPromotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromotionActionPerformed
        PromotionManagerJDialog promo = new PromotionManagerJDialog(new MainUI(), true);
        promo.setVisible(true);
    }//GEN-LAST:event_btnPromotionActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        ChangePasswordJDialog changePass = new ChangePasswordJDialog(new MainUI(), true);
        changePass.setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        CustomerManagerJDialog customer = new CustomerManagerJDialog(new javax.swing.JFrame(), true);
        customer.setVisible(true);
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriesActionPerformed
        CategoryManagerJDialog category = new CategoryManagerJDialog(new MainUI(), true);
        category.setVisible(true);
    }//GEN-LAST:event_btnCategoriesActionPerformed

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        EmployeeManagerJDialog employee = new EmployeeManagerJDialog(new MainUI(), true);
        employee.setVisible(true);
    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        PaymentManagerJDialog payment = new PaymentManagerJDialog(new MainUI(), true);
        payment.setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnExportInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportInvoiceActionPerformed
        OrderManagerJDialog order= new OrderManagerJDialog(new MainUI(), true);
        order.setVisible(true);
    }//GEN-LAST:event_btnExportInvoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            javax.swing.JFrame dummyFrame = new javax.swing.JFrame();
            dummyFrame.setUndecorated(true);
            dummyFrame.setVisible(false);
            dummyFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

            // Mở LoginJDialog với dummyFrame là parent
            LoginUI dialog = new LoginUI(dummyFrame, true);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookInfo;
    private javax.swing.JButton btnCategories;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExportInvoice;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnPromotion;
    private javax.swing.JButton btnRevenue;
    private javax.swing.JLabel lblProfile;
    // End of variables declaration//GEN-END:variables
}
