/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectone.ui;

import com.mycompany.projectone.ui.manager.AccountManagerJDialog;
import com.mycompany.projectone.ui.manager.BookManagerJDialog;
import com.mycompany.projectone.ui.manager.CategoryManagerJDialog;
import com.mycompany.projectone.ui.manager.CustomerManagerJDialog;
import com.mycompany.projectone.ui.manager.EmployeeManagerJDialog;
import com.mycompany.projectone.ui.manager.OrderManagerJDialog;
import com.mycompany.projectone.ui.manager.PaymentManagerJDialog;
import com.mycompany.projectone.ui.manager.PromotionManagerJDialog;
import com.mycompany.projectone.ui.manager.PurchaseReceiptJDialog;
import com.mycompany.projectone.ui.manager.RegisterAccountJDialog;
import com.mycompany.projectone.ui.manager.RevenueManagerJDialog;
import com.mycompany.projectone.ui.manager.StockManagerJDialog;
import com.mycompany.projectone.ui.manager.SupplierManagerJDialog;
import com.mycompany.projectone.util.XDialog;

/**
 *
 * @author Gaudomun
 */
public class New_MainUI extends javax.swing.JFrame {

    /**
     * Creates new form New_MainUI
     */
    public New_MainUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControl = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        btnBookMgr = new javax.swing.JButton();
        btnCategoryMgr = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnPromotionMgr = new javax.swing.JButton();
        btnPaymentMgr = new javax.swing.JButton();
        btnRevenueMgr = new javax.swing.JButton();
        btnPurchaseReceiptMgr = new javax.swing.JButton();
        btnStockMgr = new javax.swing.JButton();
        btnSupplierMgr = new javax.swing.JButton();
        btnExportInvoice = new javax.swing.JButton();
        btnAccountMgr = new javax.swing.JButton();
        btnRegisterAcc = new javax.swing.JButton();
        btnChangePassword = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlComponents = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlBackground = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BOOKSTORE");
        setPreferredSize(new java.awt.Dimension(1080, 600));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        pnlControl.setOpaque(false);
        pnlControl.setPreferredSize(new java.awt.Dimension(1080, 600));
        pnlControl.setLayout(new java.awt.BorderLayout());

        pnlButtons.setPreferredSize(new java.awt.Dimension(1080, 200));
        pnlButtons.setLayout(new java.awt.GridLayout(3, 5, 10, 10));

        btnBookMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnBookMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnBookMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnBookMgr.setText("THÔNG TIN SÁCH");
        btnBookMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnBookMgr);

        btnCategoryMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnCategoryMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCategoryMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnCategoryMgr.setText("THỂ LOẠI SÁCH");
        btnCategoryMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoryMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCategoryMgr);

        btnCustomers.setBackground(new java.awt.Color(0, 51, 204));
        btnCustomers.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomers.setText("QUẢN LÝ KHÁCH HÀNG");
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCustomers);

        btnEmployee.setBackground(new java.awt.Color(0, 51, 204));
        btnEmployee.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployee.setText("QUẢN LÝ NHÂN VIÊN");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });
        pnlButtons.add(btnEmployee);

        btnPromotionMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnPromotionMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnPromotionMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnPromotionMgr.setText("QUẢN LÝ KHUYẾN MÃI");
        btnPromotionMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromotionMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnPromotionMgr);

        btnPaymentMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnPaymentMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnPaymentMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnPaymentMgr.setText("QUẢN LÝ THANH TOÁN");
        btnPaymentMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnPaymentMgr);

        btnRevenueMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnRevenueMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnRevenueMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnRevenueMgr.setText("THỐNG KÊ DOANH THU");
        btnRevenueMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnRevenueMgr);

        btnPurchaseReceiptMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnPurchaseReceiptMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnPurchaseReceiptMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnPurchaseReceiptMgr.setText("QUẢN LÝ PHIẾU NHẬP");
        btnPurchaseReceiptMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseReceiptMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnPurchaseReceiptMgr);

        btnStockMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnStockMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnStockMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnStockMgr.setText("QUẢN LÝ TỒN KHO");
        btnStockMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnStockMgr);

        btnSupplierMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnSupplierMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnSupplierMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnSupplierMgr.setText("QUẢN LÝ NHÀ CUNG CẤP");
        btnSupplierMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSupplierMgr);

        btnExportInvoice.setBackground(new java.awt.Color(0, 51, 204));
        btnExportInvoice.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnExportInvoice.setForeground(new java.awt.Color(255, 255, 255));
        btnExportInvoice.setText("XUẤT HÓA ĐƠN");
        btnExportInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportInvoiceActionPerformed(evt);
            }
        });
        pnlButtons.add(btnExportInvoice);

        btnAccountMgr.setBackground(new java.awt.Color(0, 51, 204));
        btnAccountMgr.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnAccountMgr.setForeground(new java.awt.Color(255, 255, 255));
        btnAccountMgr.setText("QUẢN LÝ TÀI KHOẢN");
        btnAccountMgr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountMgrActionPerformed(evt);
            }
        });
        pnlButtons.add(btnAccountMgr);

        btnRegisterAcc.setBackground(new java.awt.Color(0, 51, 204));
        btnRegisterAcc.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnRegisterAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterAcc.setText("TẠO TÀI KHOẢN");
        btnRegisterAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterAccActionPerformed(evt);
            }
        });
        pnlButtons.add(btnRegisterAcc);

        btnChangePassword.setBackground(new java.awt.Color(0, 51, 204));
        btnChangePassword.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnChangePassword.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePassword.setText("ĐỔI MẬT KHẨU");
        btnChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePasswordActionPerformed(evt);
            }
        });
        pnlButtons.add(btnChangePassword);

        btnExit.setBackground(new java.awt.Color(0, 51, 204));
        btnExit.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("THOÁT ỨNG DỤNG");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        pnlButtons.add(btnExit);

        pnlControl.add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        pnlComponents.setOpaque(false);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Sylfaen", 1, 50)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("POLY BOOKSTORE");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setName(""); // NOI18N

        javax.swing.GroupLayout pnlComponentsLayout = new javax.swing.GroupLayout(pnlComponents);
        pnlComponents.setLayout(pnlComponentsLayout);
        pnlComponentsLayout.setHorizontalGroup(
            pnlComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentsLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(679, Short.MAX_VALUE))
        );
        pnlComponentsLayout.setVerticalGroup(
            pnlComponentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComponentsLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pnlControl.add(pnlComponents, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlControl);

        pnlBackground.setPreferredSize(new java.awt.Dimension(1080, 675));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book_background.jpg")) );

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1414, Short.MAX_VALUE)
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnlBackground);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookMgrActionPerformed
        BookManagerJDialog bookDialog = new BookManagerJDialog();
        bookDialog.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btnBookMgrActionPerformed

    private void btnCategoryMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoryMgrActionPerformed
        CategoryManagerJDialog category = new CategoryManagerJDialog(new MainUI(), true);
        category.setVisible(true);
    }//GEN-LAST:event_btnCategoryMgrActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        CustomerManagerJDialog customer = new CustomerManagerJDialog(new javax.swing.JFrame(), true);
        customer.setVisible(true);
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        EmployeeManagerJDialog employee = new EmployeeManagerJDialog(new MainUI(), true);
        employee.setVisible(true);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnPromotionMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromotionMgrActionPerformed
        PromotionManagerJDialog promo = new PromotionManagerJDialog(new MainUI(), true);
        promo.setVisible(true);
    }//GEN-LAST:event_btnPromotionMgrActionPerformed

    private void btnPaymentMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentMgrActionPerformed
        PaymentManagerJDialog payment = new PaymentManagerJDialog(new MainUI(), true);
        payment.setVisible(true);
    }//GEN-LAST:event_btnPaymentMgrActionPerformed

    private void btnRevenueMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueMgrActionPerformed
        RevenueManagerJDialog revenue = new RevenueManagerJDialog(new MainUI(), true);
        revenue.setVisible(true);
    }//GEN-LAST:event_btnRevenueMgrActionPerformed

    private void btnExportInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportInvoiceActionPerformed
        OrderManagerJDialog order= new OrderManagerJDialog(new MainUI(), true);
        order.setVisible(true);
    }//GEN-LAST:event_btnExportInvoiceActionPerformed

    private void btnChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePasswordActionPerformed
        ChangePasswordJDialog changePass = new ChangePasswordJDialog(new MainUI(), true);
        changePass.setVisible(true);
    }//GEN-LAST:event_btnChangePasswordActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       if(XDialog.confirm("Bạn chắc chắn muốn xóa?")){
           this.dispose();
       }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSupplierMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierMgrActionPerformed
        SupplierManagerJDialog managerJDialog = new SupplierManagerJDialog(this, true);
        managerJDialog.setVisible(true);
    }//GEN-LAST:event_btnSupplierMgrActionPerformed

    private void btnPurchaseReceiptMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseReceiptMgrActionPerformed
        PurchaseReceiptJDialog purchaseReceiptDialog = new PurchaseReceiptJDialog(this, true);
        purchaseReceiptDialog.setVisible(true);
    }//GEN-LAST:event_btnPurchaseReceiptMgrActionPerformed

    private void btnAccountMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountMgrActionPerformed
        AccountManagerJDialog accountDialog = new AccountManagerJDialog(this, true);
        accountDialog.setVisible(true);
    }//GEN-LAST:event_btnAccountMgrActionPerformed

    private void btnStockMgrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockMgrActionPerformed
        StockManagerJDialog stockDialog = new StockManagerJDialog(this, true);
        stockDialog.setVisible(true);
    }//GEN-LAST:event_btnStockMgrActionPerformed

    private void btnRegisterAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterAccActionPerformed
        RegisterAccountJDialog registerDialog = new RegisterAccountJDialog(this, true);
        registerDialog.setVisible(true);
    }//GEN-LAST:event_btnRegisterAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 javax.swing.JFrame dummyFrame = new javax.swing.JFrame();
            dummyFrame.setUndecorated(true);
            dummyFrame.setVisible(false);
            dummyFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);

            // Mở LoginJDialog với dummyFrame là parent
            LoginUI dialog = new LoginUI(dummyFrame, true);
            dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccountMgr;
    private javax.swing.JButton btnBookMgr;
    private javax.swing.JButton btnCategoryMgr;
    private javax.swing.JButton btnChangePassword;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExportInvoice;
    private javax.swing.JButton btnPaymentMgr;
    private javax.swing.JButton btnPromotionMgr;
    private javax.swing.JButton btnPurchaseReceiptMgr;
    private javax.swing.JButton btnRegisterAcc;
    private javax.swing.JButton btnRevenueMgr;
    private javax.swing.JButton btnStockMgr;
    private javax.swing.JButton btnSupplierMgr;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlComponents;
    private javax.swing.JPanel pnlControl;
    // End of variables declaration//GEN-END:variables
}
